### ISSUE TITLE
Infinity seems Broken

### ISSUE THREAD

**Issue by klockeph** [Jacorb90/Dist-Inc.github.io#45]
Hi,

I unlocked infinity yesterday and got my first endorsement. A short time later, the infinity tab disappeared and I had to get my first endorsement again.

Then I played until I got ~11 endorsements, closed the game and when I reopened it today, I have to start again with my first endorsement.

I'm playing on android (in google chrome), with the website added to my Homescreen.

Do you have any idea why this could happen?

**Comment by Jacorb90** [comment]
Hello,

Alright, that's very odd... I suspect it has something to do with being on android, since this game has not been thoroughly tested there (I don't have an android so that may be part of it). 

I suspect that for some reason your autosave was disabled, although I have no idea as to why that may have happened...

Could you come join my discord (link in the game's option menu) and DM me so I can get a little more information?

If you'd rather not do that, I suppose we could just do it through github but that would be slower...

Thanks, Jacorb.

**Comment by klockeph** [comment]
Sure, I joined your discord; could you give me your username?

**Comment by Jacorb90** [comment]
Yep, my username is Jacorb#8747
